default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: dev
  password: root

development:
  <<: *default
  database: n1_development
  username: dev
  password: root

test:
  <<: *default
  database: n1_development_test
  username: dev
  password: root

production:
  <<: *default
  database: n1_production
